import { Inter } from "next/font/google"
import "../globals/globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js"
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" style={{ height: "100vh" }}>
            <body
                className={`${inter.className}`}
                style={{ height: "100vh", margin: 0 }}
            >
                {children}
            </body>
        </html>
    )
}
