 name: Node.js CI

 on:
   push:
     branches: [ "main" ]
     paths-ignore:
       - '**.yml'
       
 jobs:
   build_NextJS:
     name: build_NextJS
     runs-on: self-hosted
    
     steps:
     - uses: actions/checkout@v3
       with:
         clean: false

     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
        node-version: '18'
        
     - name: install deps
       run: yarn install
       
     - name: Build Homepage
       run: yarn build
       
     - name: turn on app
       run: pm2 startOrReload ecosystem.config.js
