 name: Node.js CI

 on:
   push:
     branches: [ "main" ]
     paths-ignore:
       - '**.yml'
       
 jobs:
   build_NextJS:
     name: build_NextJS
     runs-on: self-hosted
#      defaults:
#        run:
#          working-directory: ./frontend
#          shell: bash
     strategy:
       matrix:
         node-version: [18.x]
     steps:
     - uses: actions/checkout@v3
       with:
         clean: false
     - name: install deps
       run: yarn install
     - name: Build Homepage
       run: yarn build
     - name: turn on app
       run: pm2 startOrReload ecosystem.config.js
